site_name: BobNet Documentation
nav:
  - Home: index.md
  - Get Started: getstarted.md
  - Use Custom JSON: usemyjson.md
  - Use Check: usecheck.md
  - BobNet on GitHub: https://github.com/Freakybob-Team/bobnet
  - BobNet Docs on GitHub: https://github.com/Freakybob-Team/bobnet-docs
theme:
  name: swan
  favicon: images/favicon.ico
markdown_extensions:
  - admonition
plugins:
  - rss
  - badges
  - search
  - git-authors
  - git-revision-date-localized
  - live-edit
site_description: BobNet Docs RSS
site_name: BobNet Documentation
site_url: https://Freakybob-Team.github.io/bobnet-docs/