site_name: BobNet Documentation
nav:
  - Home: index.md
  - Get Started: getstarted.md
  - Use Custom JSON: usemyjson.md
  - Use Check: usecheck.md
  - BobNet on GitHub: https://github.com/Freakybob-Team/bobnet
  - BobNet Docs on GitHub: https://github.com/Freakybob-Team/bobnet-docs
theme: swan
markdown_extensions:
  - admonition